# Generated by Django 5.0.4 on 2024-05-17 08:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('registrationNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceType', models.CharField(blank=True, max_length=255, null=True)),
                ('chassisNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('trackingCode', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='deviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('gpsTime', models.DateTimeField()),
                ('gprsTime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('speedKph', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('odometer', models.BigIntegerField()),
                ('gpsSignal', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviceLocation', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='canInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('vehicleBattery', models.BigIntegerField(null=True)),
                ('stateOfCharge', models.IntegerField(null=True)),
                ('AMinCellVolt', models.BigIntegerField(null=True)),
                ('APackVoltageValue', models.BigIntegerField(null=True)),
                ('APackCurrentValue', models.BigIntegerField(null=True)),
                ('batteryTemperature', models.BigIntegerField(null=True)),
                ('ASOCValue', models.BigIntegerField(null=True)),
                ('BFaultRank', models.BigIntegerField(null=True)),
                ('totalRegenerationEnergy', models.BigIntegerField(null=True)),
                ('BPackCurrentValue', models.BigIntegerField(null=True)),
                ('BMaxCellVolt', models.BigIntegerField(null=True)),
                ('ChargerGunDetected2', models.BigIntegerField(null=True)),
                ('AMaxCellVolt', models.BigIntegerField(null=True)),
                ('BMinCellVolt', models.BigIntegerField(null=True)),
                ('BPackVoltageValue', models.BigIntegerField(null=True)),
                ('AFaultRank', models.BigIntegerField(null=True)),
                ('BSOCValue', models.BigIntegerField(null=True)),
                ('distanceToEmpty', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canInfo_devices', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('timestamp', models.BigIntegerField(null=True)),
                ('latitude', models.BigIntegerField(null=True)),
                ('longitude', models.BigIntegerField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=1000)),
                ('alarmType', models.IntegerField(null=True)),
                ('limit', models.IntegerField(null=True)),
                ('severity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_alerts', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='deviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceStatus', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='dinputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('input_1', models.IntegerField(null=True)),
                ('input_2', models.IntegerField(null=True)),
                ('input_3', models.IntegerField(null=True)),
                ('input_4', models.IntegerField(null=True)),
                ('input_5', models.IntegerField(null=True)),
                ('input_6', models.IntegerField(null=True)),
                ('input_7', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_dinputs', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('embedUrl', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='database.devices')),
            ],
        ),
        migrations.CreateModel(
            name='todaysDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=100)),
                ('todayKms', models.IntegerField(null=True)),
                ('todayMovementTime', models.IntegerField(null=True)),
                ('todayIdleTime', models.IntegerField(null=True)),
                ('todayDriveCount', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_todaysDrive', to='database.devices')),
            ],
        ),
    ]
