# Generated by Django 5.0.4 on 2024-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_alerts_latitude_alter_alerts_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True),
        ),
    ]
