# Generated by Django 5.0.4 on 2024-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_alerts_latitude_alter_alerts_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
    ]
