# Generated by Django 5.0.4 on 2024-06-12 07:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_test_models_test_models2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('gpsTime', models.DateTimeField()),
                ('gprsTime', models.DateTimeField()),
                ('device_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('altitude', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('speedKph', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('odometer', models.BigIntegerField()),
                ('gpsSignal', models.IntegerField()),
                ('vehicleBattery', models.BigIntegerField(null=True)),
                ('stateOfCharge', models.IntegerField(null=True)),
                ('AMinCellVolt', models.BigIntegerField(null=True)),
                ('APackVoltageValue', models.BigIntegerField(null=True)),
                ('APackCurrentValue', models.BigIntegerField(null=True)),
                ('batteryTemperature', models.BigIntegerField(null=True)),
                ('ASOCValue', models.BigIntegerField(null=True)),
                ('BFaultRank', models.BigIntegerField(null=True)),
                ('totalRegenerationEnergy', models.BigIntegerField(null=True)),
                ('BPackCurrentValue', models.BigIntegerField(null=True)),
                ('BMaxCellVolt', models.BigIntegerField(null=True)),
                ('ChargerGunDetected2', models.BigIntegerField(null=True)),
                ('AMaxCellVolt', models.BigIntegerField(null=True)),
                ('BMinCellVolt', models.BigIntegerField(null=True)),
                ('BPackVoltageValue', models.BigIntegerField(null=True)),
                ('AFaultRank', models.BigIntegerField(null=True)),
                ('BSOCValue', models.BigIntegerField(null=True)),
                ('distanceToEmpty', models.BigIntegerField(null=True)),
                ('timestamp', models.BigIntegerField(null=True)),
                ('alert_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('alert_address', models.CharField(max_length=1000)),
                ('alarmType', models.IntegerField(null=True)),
                ('limit', models.IntegerField(null=True)),
                ('severity', models.IntegerField(null=True)),
                ('todayKms', models.IntegerField(null=True)),
                ('todayMovementTime', models.IntegerField(null=True)),
                ('todayIdleTime', models.IntegerField(null=True)),
                ('todayDriveCount', models.IntegerField(null=True)),
                ('embedUrl', models.CharField(max_length=500)),
                ('input_1', models.IntegerField(null=True)),
                ('input_2', models.IntegerField(null=True)),
                ('input_3', models.IntegerField(null=True)),
                ('input_4', models.IntegerField(null=True)),
                ('input_5', models.IntegerField(null=True)),
                ('input_6', models.IntegerField(null=True)),
                ('input_7', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_device_id', to='database.devices')),
            ],
        ),
        migrations.DeleteModel(
            name='test_models',
        ),
        migrations.DeleteModel(
            name='test_models2',
        ),
    ]
