# Generated by Django 5.0.4 on 2024-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_masterdevicedetails_delete_test_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevicedetails',
            name='alert_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
