# Generated by Django 5.0.4 on 2024-06-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_devicestatus_device_alter_links_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevicedetails',
            name='gprsTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdevicedetails',
            name='gpsTime',
            field=models.DateTimeField(null=True),
        ),
    ]
