# Generated by Django 5.0.4 on 2024-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_masterdevicedetails_gprstime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevicedetails',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
    ]
