# Generated by Django 5.0.4 on 2024-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_masterdevicedetails_gpssignal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevicedetails',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
