# Generated by Django 5.0.4 on 2024-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_masterdevicedetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevicedetails',
            name='embedUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
