# Generated by Django 5.0.4 on 2024-06-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_noidaextentoincedointellectstops'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noidaextentoincedointellectstops',
            table='noida exten_to_incedointellect_route_stops',
        ),
    ]
