# Generated by Django 5.0.4 on 2024-07-28 06:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_caninfo_device_remove_devicelocation_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargingsation',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'chargingSation',
                'managed': False,
            },
        ),
    ]
