# Generated by Django 5.0.4 on 2024-08-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_chargingsation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdevicedetails',
            old_name='limit',
            new_name='limits',
        ),
    ]
