# Generated by Django 5.0.4 on 2024-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_rename_limit_masterdevicedetails_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
